spring:
  application:
    name: microservice-api-gateway

security:
  user:
    name: user
    password: password
    role:
      - user
      - admin
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      authorized-grant-types:
        password
        refresh_token
    resource:
      userInfoUri: https://localhost:8050/user
      preferTokenInfo: false     

server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: microservice-provider-user          # 需要忽视的服务(配置后将不会被路由)
  routes:
    movie:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /movie/**                                   # 想要映射到的路径
      service-id: microservice-consumer-movie-ribbon    # Eureka中的serviceId
